//@version=6
indicator("Supported array fixed simple array return qualifier")

ints = array.from(1, 2, 3)
floats = array.from(1.0, 2.0, 3.0)
float_matrix = matrix.new<float>(1, 3, 0.0)
int_matrix = matrix.new<int>(1, 3, 0)

matrix.add_row(float_matrix, 0, array.standardize(ints))
matrix.add_col(float_matrix, 0, floats.standardize())
matrix.add_row(float_matrix, 0, array.standardize(floats))
matrix.add_col(float_matrix, 0, ints.standardize())
matrix.add_row(int_matrix, 0, array.sort_indices(floats))
matrix.add_col(int_matrix, 0, ints.sort_indices())
matrix.add_row(int_matrix, 0, array.sort_indices(ints))
matrix.add_col(int_matrix, 0, floats.sort_indices())
