//@version=5
indicator("Supported user type history")

type Point
    float x

type Wrapper
    Point point

dyn = bar_index == 0 ? na : 1

p = Point.new(close)
p_alias = p
p_prior = p[1]
p_dynamic = p[dyn]
alias_prior = p_alias[1]

wrapped = Wrapper.new(Point.new(high))
wrapped_prior = wrapped[1]
wrapped_dynamic = wrapped[dyn]

plot(p_prior.x + p_dynamic.x + alias_prior.x + wrapped_prior.point.x + wrapped_dynamic.point.x)
