//@version=6
indicator("Supported drawing object return qualifier")

label_id = label.new(bar_index, high, "label")
line_id = line.new(bar_index, low, bar_index + 1, high)
box_id = box.new(bar_index, high, bar_index + 1, low)
table_id = table.new(position.top_left, 1, 1)
fill_id = linefill.new(line_id, line.new(bar_index + 2, low, bar_index + 3, high), color.green)
points = array.from(chart.point.from_index(bar_index, close), chart.point.from_index(bar_index + 1, close + 1))
polyline_id = polyline.new(points, line_color=color.red)

label.set_text(label_id, "updated")
line.set_x1(line_id, bar_index)
box.set_text(box_id, "updated")
table.cell(table_id, 0, 0, "cell")
linefill.set_color(fill_id, color.red)
polyline.delete(polyline_id)
