//@version=6
indicator("Supported for-in expression linefill")

upper = line.new(bar_index, high, bar_index + 1, high + 1)
middle = line.new(bar_index + 2, close, bar_index + 3, close + 1)
lower = line.new(bar_index + 4, low, bar_index + 5, low - 1)
values = array.from(linefill.new(upper, middle, color.green), linefill.new(middle, lower, color.red))
result = for value in values
    value

plot(line.get_x1(linefill.get_line1(result)) == bar_index + 2 ? 1 : 0)
