//@version=5
strategy("Supported strategy trade count interactions")

scale(value) => value * 2

if strategy.opentrades > 0
    plot(scale(strategy.opentrades))
else
    plot(strategy.closedtrades[1])

state = switch strategy.closedtrades > 0
    true => strategy.closedtrades
    => strategy.opentrades

sum = strategy.closedtrades * 0
for i = 0 to 1
    sum := sum + strategy.opentrades

j = 0
while j < strategy.opentrades
    sum := sum + 1
    j := j + 1

plot(state + sum)
