//@version=6
indicator("Supported array element series return qualifier")

get_values = array.from(1, 2)
remove_values = array.from(1, 2)
pop_values = array.from(1, 2)
shift_values = array.from(1, 2)
first_values = array.from(1, 2)
last_values = array.from(1, 2)

method_get_values = array.from(1, 2)
method_remove_values = array.from(1, 2)
method_pop_values = array.from(1, 2)
method_shift_values = array.from(1, 2)
method_first_values = array.from(1, 2)
method_last_values = array.from(1, 2)

plot(array.get(get_values, 0) + array.remove(remove_values, 0))
plot(array.pop(pop_values) + array.shift(shift_values))
plot(array.first(first_values) + array.last(last_values))

plot(method_get_values.get(0) + method_remove_values.remove(0))
plot(method_pop_values.pop() + method_shift_values.shift())
plot(method_first_values.first() + method_last_values.last())
