//@version=6
indicator("Unsupported array SameAsArg array return qualifier")

ints = array.from(1, 2, 3)
more_ints = array.from(4, 5, 6)
floats = array.from(1.0, 2.0, 3.0)
more_floats = array.from(4.0, 5.0, 6.0)
int_matrix = matrix.new<int>(1, 3, 0)
float_matrix = matrix.new<float>(1, 3, 0.0)

matrix.add_row(float_matrix, 0, array.copy(ints))
matrix.add_col(int_matrix, 0, floats.copy())
matrix.add_row(float_matrix, 0, array.slice(ints, 0, 2))
matrix.add_col(int_matrix, 0, floats.slice(0, 2))
matrix.add_row(float_matrix, 0, array.concat(ints, more_ints))
matrix.add_col(int_matrix, 0, floats.concat(more_floats))
