//@version=6
indicator("Unsupported str promoted string simple return qualifier")

text = timeframe.period

substring_text = str.substring(text, 0, 1)
repeat_text = str.repeat(text, 2)
replace_text = str.replace(text, "D", "W")
replace_all_text = str.replace_all(text, "D", "W")

substring_length = str.length(substring_text)
repeat_length = str.length(repeat_text)
replace_length = str.length(replace_text)
replace_all_length = str.length(replace_all_text)

plot(close, show_last=substring_length)
plot(open, show_last=repeat_length)
plot(high, show_last=replace_length)
plot(low, show_last=replace_all_length)
