//@version=6
indicator("Unsupported drawing object return qualifier")

label_id = label.new(bar_index, high, "label")
line_id = line.new(bar_index, low, bar_index + 1, high)
box_id = box.new(bar_index, high, bar_index + 1, low)
table_id = table.new(position.top_left, 1, 1)
fill_id = linefill.new(line_id, line.new(bar_index + 2, low, bar_index + 3, high), color.green)
points = array.from(chart.point.from_index(bar_index, close), chart.point.from_index(bar_index + 1, close + 1))
polyline_id = polyline.new(points, line_color=color.red)

hline(label_id)
hline(line_id)
hline(box_id)
hline(table_id)
hline(fill_id)
hline(polyline_id)
