//@version=5
strategy("Strategy state request")
plot(request.security(syminfo.tickerid, timeframe.period, strategy.position_size))
plot(request.security(syminfo.tickerid, timeframe.period, strategy.position_avg_price))
plot(request.security(syminfo.tickerid, timeframe.period, strategy.openprofit))
plot(request.security(syminfo.tickerid, timeframe.period, strategy.netprofit))
plot(request.security(syminfo.tickerid, timeframe.period, strategy.equity))
