struct NamedStringConstant {
    name: &'static str,
    value: &'static str,
}

const NAMED_STRING_CONSTANTS: &[NamedStringConstant] = &[
    same_string_constant("shape.xcross"),
    same_string_constant("shape.cross"),
    same_string_constant("shape.circle"),
    same_string_constant("shape.triangleup"),
    same_string_constant("shape.triangledown"),
    same_string_constant("shape.flag"),
    same_string_constant("shape.arrowup"),
    same_string_constant("shape.arrowdown"),
    same_string_constant("shape.square"),
    same_string_constant("shape.diamond"),
    same_string_constant("shape.labelup"),
    same_string_constant("shape.labeldown"),
    same_string_constant("location.abovebar"),
    same_string_constant("location.belowbar"),
    same_string_constant("location.top"),
    same_string_constant("location.bottom"),
    same_string_constant("location.absolute"),
    same_string_constant("plot.style_line"),
    same_string_constant("plot.style_stepline"),
    same_string_constant("plot.style_stepline_diamond"),
    same_string_constant("plot.style_histogram"),
    same_string_constant("plot.style_cross"),
    same_string_constant("plot.style_area"),
    same_string_constant("plot.style_columns"),
    same_string_constant("plot.style_circles"),
    same_string_constant("plot.style_linebr"),
    same_string_constant("plot.style_areabr"),
    same_string_constant("hline.style_solid"),
    same_string_constant("hline.style_dotted"),
    same_string_constant("hline.style_dashed"),
    same_string_constant("xloc.bar_index"),
    same_string_constant("xloc.bar_time"),
    same_string_constant("yloc.price"),
    same_string_constant("yloc.abovebar"),
    same_string_constant("yloc.belowbar"),
    same_string_constant("label.style_none"),
    same_string_constant("label.style_xcross"),
    same_string_constant("label.style_cross"),
    same_string_constant("label.style_triangleup"),
    same_string_constant("label.style_triangledown"),
    same_string_constant("label.style_flag"),
    same_string_constant("label.style_circle"),
    same_string_constant("label.style_arrowup"),
    same_string_constant("label.style_arrowdown"),
    same_string_constant("label.style_label_up"),
    same_string_constant("label.style_label_down"),
    same_string_constant("label.style_label_left"),
    same_string_constant("label.style_label_right"),
    same_string_constant("label.style_label_lower_left"),
    same_string_constant("label.style_label_lower_right"),
    same_string_constant("label.style_label_upper_left"),
    same_string_constant("label.style_label_upper_right"),
    same_string_constant("line.style_solid"),
    same_string_constant("line.style_dotted"),
    same_string_constant("line.style_dashed"),
    same_string_constant("line.style_arrow_left"),
    same_string_constant("line.style_arrow_right"),
    same_string_constant("line.style_arrow_both"),
    same_string_constant("extend.none"),
    same_string_constant("extend.right"),
    same_string_constant("extend.left"),
    same_string_constant("extend.both"),
    same_string_constant("size.auto"),
    same_string_constant("size.tiny"),
    same_string_constant("size.small"),
    same_string_constant("size.normal"),
    same_string_constant("size.large"),
    same_string_constant("size.huge"),
    same_string_constant("position.top_left"),
    same_string_constant("position.top_center"),
    same_string_constant("position.top_right"),
    same_string_constant("position.middle_left"),
    same_string_constant("position.middle_center"),
    same_string_constant("position.middle_right"),
    same_string_constant("position.bottom_left"),
    same_string_constant("position.bottom_center"),
    same_string_constant("position.bottom_right"),
    same_string_constant("display.all"),
    same_string_constant("display.none"),
    same_string_constant("display.pane"),
    same_string_constant("display.price_scale"),
    same_string_constant("display.status_line"),
    same_string_constant("display.data_window"),
    same_string_constant("format.mintick"),
    same_string_constant("format.price"),
    same_string_constant("format.percent"),
    same_string_constant("format.volume"),
    same_string_constant("order.ascending"),
    same_string_constant("order.descending"),
    same_string_constant("strategy.fixed"),
    same_string_constant("strategy.long"),
    same_string_constant("strategy.commission.cash_per_contract"),
    same_string_constant("strategy.commission.cash_per_order"),
    same_string_constant("strategy.commission.percent"),
    NamedStringConstant {
        name: "syminfo.basecurrency",
        value: "USD",
    },
    NamedStringConstant {
        name: "syminfo.currency",
        value: "USD",
    },
    NamedStringConstant {
        name: "syminfo.description",
        value: "Apple Inc.",
    },
    NamedStringConstant {
        name: "syminfo.prefix",
        value: "NASDAQ",
    },
    NamedStringConstant {
        name: "syminfo.root",
        value: "AAPL",
    },
    NamedStringConstant {
        name: "syminfo.session",
        value: "regular",
    },
    NamedStringConstant {
        name: "syminfo.ticker",
        value: "AAPL",
    },
    NamedStringConstant {
        name: "syminfo.tickerid",
        value: "NASDAQ:AAPL",
    },
    NamedStringConstant {
        name: "syminfo.timezone",
        value: "Etc/UTC",
    },
    NamedStringConstant {
        name: "syminfo.type",
        value: "stock",
    },
    NamedStringConstant {
        name: "syminfo.volumetype",
        value: "base",
    },
];

const fn same_string_constant(name: &'static str) -> NamedStringConstant {
    NamedStringConstant { name, value: name }
}

#[must_use]
pub fn named_string_constant(name: &str) -> Option<&'static str> {
    NAMED_STRING_CONSTANTS
        .iter()
        .find(|constant| constant.name == name)
        .map(|constant| constant.value)
}
