pub(crate) const RUNTIME_SNAPSHOT_FIXTURES: &[(&str, &str)] = &[
    (
        "runtime_basic_plot.json",
        "tests/fixtures/runtime/snapshot_plot.pine",
    ),
    (
        "runtime_plotchar.json",
        "tests/fixtures/runtime/plotchar.pine",
    ),
    (
        "runtime_plotshape.json",
        "tests/fixtures/runtime/plotshape.pine",
    ),
    (
        "runtime_plotarrow.json",
        "tests/fixtures/runtime/plotarrow.pine",
    ),
    (
        "runtime_plotbar.json",
        "tests/fixtures/runtime/plotbar.pine",
    ),
    (
        "runtime_plotcandle.json",
        "tests/fixtures/runtime/plotcandle.pine",
    ),
    (
        "runtime_color_outputs.json",
        "tests/fixtures/runtime/color_outputs.pine",
    ),
    (
        "runtime_alertcondition.json",
        "tests/fixtures/runtime/alertcondition.pine",
    ),
    ("runtime_alert.json", "tests/fixtures/runtime/alert.pine"),
    ("runtime_hline_fill.json", "tests/fixtures/runtime/io.pine"),
    (
        "runtime_label_new.json",
        "tests/fixtures/runtime/label_new.pine",
    ),
    (
        "runtime_label_options.json",
        "tests/fixtures/runtime/label_options.pine",
    ),
    (
        "runtime_label_mutation.json",
        "tests/fixtures/runtime/label_mutation.pine",
    ),
    (
        "runtime_label_delete.json",
        "tests/fixtures/runtime/label_delete.pine",
    ),
    (
        "runtime_line_new.json",
        "tests/fixtures/runtime/line_new.pine",
    ),
    (
        "runtime_line_mutation.json",
        "tests/fixtures/runtime/line_mutation.pine",
    ),
    (
        "runtime_line_delete.json",
        "tests/fixtures/runtime/line_delete.pine",
    ),
    (
        "runtime_box_new.json",
        "tests/fixtures/runtime/box_new.pine",
    ),
    (
        "runtime_box_mutation.json",
        "tests/fixtures/runtime/box_mutation.pine",
    ),
    (
        "runtime_box_delete.json",
        "tests/fixtures/runtime/box_delete.pine",
    ),
    (
        "runtime_table_new.json",
        "tests/fixtures/runtime/table_new.pine",
    ),
    (
        "runtime_table_cell.json",
        "tests/fixtures/runtime/table_cell.pine",
    ),
    (
        "runtime_strategy_empty.json",
        "tests/fixtures/runtime/strategy_no_order.pine",
    ),
    (
        "runtime_strategy_entry.json",
        "tests/fixtures/runtime/strategy_entry.pine",
    ),
    (
        "runtime_strategy_entry_limit.json",
        "tests/fixtures/runtime/strategy_entry_limit.pine",
    ),
    (
        "runtime_strategy_limit_verification_entry.json",
        "tests/fixtures/runtime/strategy_limit_verification_entry.pine",
    ),
    (
        "runtime_strategy_entry_stop.json",
        "tests/fixtures/runtime/strategy_entry_stop.pine",
    ),
    (
        "runtime_strategy_entry_stop_limit.json",
        "tests/fixtures/runtime/strategy_entry_stop_limit.pine",
    ),
    (
        "runtime_strategy_default_quantity.json",
        "tests/fixtures/runtime/strategy_default_quantity.pine",
    ),
    (
        "runtime_strategy_percent_of_equity_default_quantity.json",
        "tests/fixtures/runtime/strategy_percent_of_equity_default_quantity.pine",
    ),
    (
        "runtime_strategy_cash_default_quantity.json",
        "tests/fixtures/runtime/strategy_cash_default_quantity.pine",
    ),
    (
        "runtime_strategy_cash_default_quantity_limit.json",
        "tests/fixtures/runtime/strategy_cash_default_quantity_limit.pine",
    ),
    (
        "runtime_strategy_cash_default_quantity_override.json",
        "tests/fixtures/runtime/strategy_cash_default_quantity_override.pine",
    ),
    (
        "runtime_strategy_default_quantity_override.json",
        "tests/fixtures/runtime/strategy_default_quantity_override.pine",
    ),
    (
        "runtime_strategy_close.json",
        "tests/fixtures/runtime/strategy_close.pine",
    ),
    (
        "runtime_strategy_close_qty_partial.json",
        "tests/fixtures/runtime/strategy_close_qty_partial.pine",
    ),
    (
        "runtime_strategy_close_qty_full_clamp.json",
        "tests/fixtures/runtime/strategy_close_qty_full_clamp.pine",
    ),
    (
        "runtime_strategy_close_qty_percent_precedence.json",
        "tests/fixtures/runtime/strategy_close_qty_percent_precedence.pine",
    ),
    (
        "runtime_strategy_close_all.json",
        "tests/fixtures/runtime/strategy_close_all.pine",
    ),
    (
        "runtime_strategy_cancel_entry.json",
        "tests/fixtures/runtime/strategy_cancel_entry.pine",
    ),
    (
        "runtime_strategy_cancel_all_entry_exit.json",
        "tests/fixtures/runtime/strategy_cancel_all_entry_exit.pine",
    ),
    (
        "runtime_strategy_exit_stop.json",
        "tests/fixtures/runtime/strategy_exit_stop.pine",
    ),
    (
        "runtime_strategy_exit_limit.json",
        "tests/fixtures/runtime/strategy_exit_limit.pine",
    ),
    (
        "runtime_strategy_exit_profit.json",
        "tests/fixtures/runtime/strategy_exit_profit.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_profit_attachment.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_profit_attachment.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_loss_attachment.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_loss_attachment.pine",
    ),
    (
        "runtime_strategy_exit_loss.json",
        "tests/fixtures/runtime/strategy_exit_loss.pine",
    ),
    (
        "runtime_strategy_exit_interactions.json",
        "tests/fixtures/runtime/strategy_exit_interactions.pine",
    ),
    (
        "runtime_strategy_exit_profit_loss_interactions.json",
        "tests/fixtures/runtime/strategy_exit_profit_loss_interactions.pine",
    ),
    (
        "runtime_strategy_exit_bracket_stop_limit_limit_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_stop_limit_limit_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_stop_limit_stop_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_stop_limit_stop_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_loss_profit_profit_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_loss_profit_profit_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_loss_profit_loss_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_loss_profit_loss_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_mixed_pairs.json",
        "tests/fixtures/runtime/strategy_exit_bracket_mixed_pairs.pine",
    ),
    (
        "runtime_strategy_exit_bracket_creation_bar.json",
        "tests/fixtures/runtime/strategy_exit_bracket_creation_bar.pine",
    ),
    (
        "runtime_strategy_exit_bracket_repeated.json",
        "tests/fixtures/runtime/strategy_exit_bracket_repeated.pine",
    ),
    (
        "runtime_strategy_exit_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_omitted_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_omitted_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_bracket_invalid_leg.json",
        "tests/fixtures/runtime/strategy_exit_bracket_invalid_leg.pine",
    ),
    (
        "runtime_strategy_exit_bracket_both_hit.json",
        "tests/fixtures/runtime/strategy_exit_bracket_both_hit.pine",
    ),
    (
        "runtime_strategy_exit_bracket_state.json",
        "tests/fixtures/runtime/strategy_exit_bracket_state.pine",
    ),
    (
        "runtime_strategy_exit_bracket_interactions.json",
        "tests/fixtures/runtime/strategy_exit_bracket_interactions.pine",
    ),
    (
        "runtime_strategy_exit_trail_price_fill.json",
        "tests/fixtures/runtime/strategy_exit_trail_price_fill.pine",
    ),
    (
        "runtime_strategy_exit_trail_points_fill.json",
        "tests/fixtures/runtime/strategy_exit_trail_points_fill.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_trail_points_attachment.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_trail_points_attachment.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_stop_profit_bracket.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_stop_profit_bracket.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_loss_limit_bracket.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_loss_limit_bracket.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_loss_profit_bracket.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_loss_profit_bracket.pine",
    ),
    (
        "runtime_strategy_exit_trailing_activation_bar.json",
        "tests/fixtures/runtime/strategy_exit_trailing_activation_bar.pine",
    ),
    (
        "runtime_strategy_exit_trailing_ratchet.json",
        "tests/fixtures/runtime/strategy_exit_trailing_ratchet.pine",
    ),
    (
        "runtime_strategy_exit_trailing_repeated.json",
        "tests/fixtures/runtime/strategy_exit_trailing_repeated.pine",
    ),
    (
        "runtime_strategy_exit_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_omitted_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_omitted_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_trailing_invalid.json",
        "tests/fixtures/runtime/strategy_exit_trailing_invalid.pine",
    ),
    (
        "runtime_strategy_exit_trailing_close_cancel.json",
        "tests/fixtures/runtime/strategy_exit_trailing_close_cancel.pine",
    ),
    (
        "runtime_strategy_exit_trailing_interactions.json",
        "tests/fixtures/runtime/strategy_exit_trailing_interactions.pine",
    ),
    (
        "runtime_strategy_exit_trailing_state.json",
        "tests/fixtures/runtime/strategy_exit_trailing_state.pine",
    ),
    (
        "runtime_strategy_exit_qty_stop_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_stop_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_limit_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_limit_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_bracket_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_bracket_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_trailing_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_trailing_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_full_clamp.json",
        "tests/fixtures/runtime/strategy_exit_qty_full_clamp.pine",
    ),
    (
        "runtime_strategy_exit_qty_repeated.json",
        "tests/fixtures/runtime/strategy_exit_qty_repeated.pine",
    ),
    (
        "runtime_strategy_exit_qty_replacement.json",
        "tests/fixtures/runtime/strategy_exit_qty_replacement.pine",
    ),
    (
        "runtime_strategy_exit_qty_state.json",
        "tests/fixtures/runtime/strategy_exit_qty_state.pine",
    ),
    (
        "runtime_strategy_exit_qty_precedence_stop.json",
        "tests/fixtures/runtime/strategy_exit_qty_precedence_stop.pine",
    ),
    (
        "runtime_strategy_exit_qty_precedence_bracket.json",
        "tests/fixtures/runtime/strategy_exit_qty_precedence_bracket.pine",
    ),
    (
        "runtime_strategy_exit_qty_precedence_trailing.json",
        "tests/fixtures/runtime/strategy_exit_qty_precedence_trailing.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_stop_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_stop_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_limit_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_limit_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_stop_limit_downside_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_stop_limit_downside_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_stop_limit_upside_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_stop_limit_upside_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_bracket_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_bracket_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_mixed_bracket_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_mixed_bracket_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_bracket_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_bracket_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_single_downside_precedence.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_single_downside_precedence.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_single_upside_order.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_single_upside_order.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_single_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_single_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_state.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_host_parity.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_host_parity.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_price_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_price_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_points_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_points_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_state.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_trailing_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_trailing_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_mixed_trailing_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_mixed_trailing_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_trailing_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_trailing_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_host_parity.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_host_parity.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_single_downside_order.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_single_downside_order.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_bracket_downside_order.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_bracket_downside_order.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_mixed_side_precedence.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_mixed_side_precedence.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_activation_mixed_fill.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_activation_mixed_fill.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_replacement_mixed.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_replacement_mixed.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_mixed_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_mixed_state.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_stop_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_stop_partial.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_stop_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_stop_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_mixed_stop_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_mixed_stop_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_mixed_side_precedence.json",
        "tests/fixtures/runtime/strategy_exit_reservation_mixed_side_precedence.pine",
    ),
    (
        "runtime_strategy_exit_reservation_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_state.pine",
    ),
    (
        "runtime_strategy_exit_reservation_interactions.json",
        "tests/fixtures/runtime/strategy_exit_reservation_interactions.pine",
    ),
    (
        "runtime_strategy_exit_omitted_single_replacement.json",
        "tests/fixtures/runtime/strategy_exit_omitted_single_replacement.pine",
    ),
    (
        "runtime_strategy_exit_omitted_replaces_reservations.json",
        "tests/fixtures/runtime/strategy_exit_omitted_replaces_reservations.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_limit_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_limit_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_bracket_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_bracket_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_trailing_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_trailing_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_full.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_full.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_full_clamp.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_full_clamp.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_repeated.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_repeated.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_replacement.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_replacement.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_state.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_state.pine",
    ),
    (
        "runtime_strategy_equity.json",
        "tests/fixtures/runtime/strategy_equity.pine",
    ),
    (
        "runtime_strategy_commission_cash_per_contract.json",
        "tests/fixtures/runtime/strategy_commission_cash_per_contract.pine",
    ),
    (
        "runtime_strategy_commission_cash_per_order.json",
        "tests/fixtures/runtime/strategy_commission_cash_per_order.pine",
    ),
    (
        "runtime_strategy_commission_percent.json",
        "tests/fixtures/runtime/strategy_commission_percent.pine",
    ),
    (
        "runtime_strategy_slippage.json",
        "tests/fixtures/runtime/strategy_slippage.pine",
    ),
    (
        "runtime_strategy_exit_slippage.json",
        "tests/fixtures/runtime/strategy_exit_slippage.pine",
    ),
    (
        "runtime_strategy_limit_verification_exit.json",
        "tests/fixtures/runtime/strategy_limit_verification_exit.pine",
    ),
    (
        "runtime_strategy_position_state.json",
        "tests/fixtures/runtime/strategy_position_state.pine",
    ),
    (
        "runtime_strategy_profit_state.json",
        "tests/fixtures/runtime/strategy_profit_state.pine",
    ),
    (
        "runtime_strategy_variable_interactions.json",
        "tests/fixtures/runtime/strategy_variable_interactions.pine",
    ),
    (
        "runtime_strategy_trade_counts.json",
        "tests/fixtures/runtime/strategy_trade_counts.pine",
    ),
    (
        "runtime_strategy_closedtrades_fields.json",
        "tests/fixtures/runtime/strategy_closedtrades_fields.pine",
    ),
    (
        "runtime_strategy_opentrades_fields.json",
        "tests/fixtures/runtime/strategy_opentrades_fields.pine",
    ),
    (
        "runtime_strategy_pyramiding.json",
        "tests/fixtures/runtime/strategy_pyramiding.pine",
    ),
    (
        "runtime_strategy_pyramiding_close.json",
        "tests/fixtures/runtime/strategy_pyramiding_close.pine",
    ),
    (
        "runtime_strategy_pyramiding_close_all.json",
        "tests/fixtures/runtime/strategy_pyramiding_close_all.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_profit_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_profit_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_bracket_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_bracket_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_trail_points_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_trail_points_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_from_entry_current.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_from_entry_current.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_from_entry_persistent.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_from_entry_persistent.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_same_id.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_same_id.pine",
    ),
    (
        "runtime_strategy_margin_capital_held_long.json",
        "tests/fixtures/runtime/strategy_margin_capital_held_long.pine",
    ),
    (
        "runtime_strategy_margin_entry_affordability.json",
        "tests/fixtures/runtime/strategy_margin_entry_affordability_long.pine",
    ),
    (
        "runtime_strategy_margin_call_long.json",
        "tests/fixtures/runtime/strategy_margin_call_long.pine",
    ),
    (
        "runtime_strategy_trade_outcome_counts.json",
        "tests/fixtures/runtime/strategy_trade_outcome_counts.pine",
    ),
    (
        "runtime_strategy_exit_trade_counts.json",
        "tests/fixtures/runtime/strategy_exit_trade_counts.pine",
    ),
];
