pub(crate) const RUNTIME_SNAPSHOT_FIXTURES: &[(&str, &str)] = &[
    (
        "runtime_basic_plot.json",
        "tests/fixtures/runtime/snapshot_plot.pine",
    ),
    (
        "runtime_plotchar.json",
        "tests/fixtures/runtime/plotchar.pine",
    ),
    (
        "runtime_plotshape.json",
        "tests/fixtures/runtime/plotshape.pine",
    ),
    (
        "runtime_plotarrow.json",
        "tests/fixtures/runtime/plotarrow.pine",
    ),
    (
        "runtime_plotbar.json",
        "tests/fixtures/runtime/plotbar.pine",
    ),
    (
        "runtime_plotcandle.json",
        "tests/fixtures/runtime/plotcandle.pine",
    ),
    (
        "runtime_color_outputs.json",
        "tests/fixtures/runtime/color_outputs.pine",
    ),
    ("runtime_colors.json", "tests/fixtures/runtime/colors.pine"),
    (
        "runtime_generic_input.json",
        "tests/fixtures/runtime/generic_input.pine",
    ),
    (
        "runtime_global_series.json",
        "tests/fixtures/runtime/global_series.pine",
    ),
    ("runtime_inputs.json", "tests/fixtures/runtime/inputs.pine"),
    (
        "runtime_barstate.json",
        "tests/fixtures/runtime/barstate.pine",
    ),
    (
        "runtime_session.json",
        "tests/fixtures/runtime/session.pine",
    ),
    ("runtime_casts.json", "tests/fixtures/runtime/casts.pine"),
    (
        "runtime_strings.json",
        "tests/fixtures/runtime/strings.pine",
    ),
    (
        "runtime_array_helpers.json",
        "tests/fixtures/runtime/array_helpers.pine",
    ),
    ("runtime_array.json", "tests/fixtures/runtime/array.pine"),
    (
        "runtime_array_methods.json",
        "tests/fixtures/runtime/array_methods.pine",
    ),
    (
        "runtime_computed_array_operands.json",
        "tests/fixtures/runtime/computed_array_operands.pine",
    ),
    (
        "runtime_array_from.json",
        "tests/fixtures/runtime/array_from.pine",
    ),
    (
        "runtime_array_insert_remove.json",
        "tests/fixtures/runtime/array_insert_remove.pine",
    ),
    (
        "runtime_array_fill.json",
        "tests/fixtures/runtime/array_fill.pine",
    ),
    (
        "runtime_array_references.json",
        "tests/fixtures/runtime/array_references.pine",
    ),
    (
        "runtime_array_search.json",
        "tests/fixtures/runtime/array_search.pine",
    ),
    (
        "runtime_array_statistics.json",
        "tests/fixtures/runtime/array_statistics.pine",
    ),
    (
        "runtime_array_ordering.json",
        "tests/fixtures/runtime/array_ordering.pine",
    ),
    (
        "runtime_array_join.json",
        "tests/fixtures/runtime/array_join.pine",
    ),
    (
        "runtime_array_slice_concat.json",
        "tests/fixtures/runtime/array_slice_concat.pine",
    ),
    (
        "runtime_timeframe.json",
        "tests/fixtures/runtime/timeframe.pine",
    ),
    (
        "runtime_time_components.json",
        "tests/fixtures/runtime/time_components.pine",
    ),
    ("runtime_udf.json", "tests/fixtures/runtime/udf.pine"),
    ("runtime_na.json", "tests/fixtures/runtime/na.pine"),
    (
        "runtime_computed_lengths.json",
        "tests/fixtures/runtime/computed_lengths.pine",
    ),
    (
        "runtime_conditional_ta.json",
        "tests/fixtures/runtime/conditional_ta.pine",
    ),
    ("runtime_ta.json", "tests/fixtures/runtime/ta.pine"),
    ("runtime_stoch.json", "tests/fixtures/runtime/stoch.pine"),
    ("runtime_wpr.json", "tests/fixtures/runtime/wpr.pine"),
    ("runtime_atr.json", "tests/fixtures/runtime/atr.pine"),
    (
        "runtime_supertrend.json",
        "tests/fixtures/runtime/supertrend.pine",
    ),
    ("runtime_dmi.json", "tests/fixtures/runtime/dmi.pine"),
    ("runtime_sar.json", "tests/fixtures/runtime/sar.pine"),
    ("runtime_cross.json", "tests/fixtures/runtime/cross.pine"),
    ("runtime_mom.json", "tests/fixtures/runtime/mom.pine"),
    ("runtime_roc.json", "tests/fixtures/runtime/roc.pine"),
    ("runtime_trend.json", "tests/fixtures/runtime/trend.pine"),
    (
        "runtime_barssince.json",
        "tests/fixtures/runtime/barssince.pine",
    ),
    (
        "runtime_valuewhen.json",
        "tests/fixtures/runtime/valuewhen.pine",
    ),
    (
        "runtime_extremes.json",
        "tests/fixtures/runtime/extremes.pine",
    ),
    (
        "runtime_extreme_bars.json",
        "tests/fixtures/runtime/extreme_bars.pine",
    ),
    ("runtime_swma.json", "tests/fixtures/runtime/swma.pine"),
    ("runtime_alma.json", "tests/fixtures/runtime/alma.pine"),
    ("runtime_linreg.json", "tests/fixtures/runtime/linreg.pine"),
    (
        "runtime_accdist.json",
        "tests/fixtures/runtime/accdist.pine",
    ),
    ("runtime_iii.json", "tests/fixtures/runtime/iii.pine"),
    ("runtime_nvi.json", "tests/fixtures/runtime/nvi.pine"),
    ("runtime_obv.json", "tests/fixtures/runtime/obv.pine"),
    ("runtime_pvi.json", "tests/fixtures/runtime/pvi.pine"),
    ("runtime_pvt.json", "tests/fixtures/runtime/pvt.pine"),
    ("runtime_vwap.json", "tests/fixtures/runtime/vwap.pine"),
    ("runtime_wad.json", "tests/fixtures/runtime/wad.pine"),
    ("runtime_wvad.json", "tests/fixtures/runtime/wvad.pine"),
    (
        "runtime_correlation.json",
        "tests/fixtures/runtime/correlation.pine",
    ),
    (
        "runtime_covariance.json",
        "tests/fixtures/runtime/covariance.pine",
    ),
    ("runtime_median.json", "tests/fixtures/runtime/median.pine"),
    ("runtime_mode.json", "tests/fixtures/runtime/mode.pine"),
    (
        "runtime_percentile_linear_interpolation.json",
        "tests/fixtures/runtime/percentile_linear_interpolation.pine",
    ),
    (
        "runtime_percentile_nearest_rank.json",
        "tests/fixtures/runtime/percentile_nearest_rank.pine",
    ),
    (
        "runtime_percentrank.json",
        "tests/fixtures/runtime/percentrank.pine",
    ),
    ("runtime_stdev.json", "tests/fixtures/runtime/stdev.pine"),
    (
        "runtime_variance.json",
        "tests/fixtures/runtime/variance.pine",
    ),
    ("runtime_range.json", "tests/fixtures/runtime/range.pine"),
    ("runtime_dev.json", "tests/fixtures/runtime/dev.pine"),
    ("runtime_vwma.json", "tests/fixtures/runtime/vwma.pine"),
    ("runtime_mfi.json", "tests/fixtures/runtime/mfi.pine"),
    ("runtime_wma.json", "tests/fixtures/runtime/wma.pine"),
    ("runtime_hma.json", "tests/fixtures/runtime/hma.pine"),
    ("runtime_if.json", "tests/fixtures/runtime/if.pine"),
    (
        "runtime_dema_tema.json",
        "tests/fixtures/runtime/dema_tema.pine",
    ),
    ("runtime_macd.json", "tests/fixtures/runtime/macd.pine"),
    ("runtime_tsi.json", "tests/fixtures/runtime/tsi.pine"),
    ("runtime_cmo.json", "tests/fixtures/runtime/cmo.pine"),
    ("runtime_cci.json", "tests/fixtures/runtime/cci.pine"),
    ("runtime_cog.json", "tests/fixtures/runtime/cog.pine"),
    ("runtime_ao.json", "tests/fixtures/runtime/ao.pine"),
    ("runtime_bop.json", "tests/fixtures/runtime/bop.pine"),
    ("runtime_bb.json", "tests/fixtures/runtime/bb.pine"),
    ("runtime_bbw.json", "tests/fixtures/runtime/bbw.pine"),
    ("runtime_kc.json", "tests/fixtures/runtime/kc.pine"),
    ("runtime_kcw.json", "tests/fixtures/runtime/kcw.pine"),
    ("runtime_pivots.json", "tests/fixtures/runtime/pivots.pine"),
    (
        "runtime_pivot_point_levels.json",
        "tests/fixtures/runtime/pivot_point_levels.pine",
    ),
    ("runtime_cum.json", "tests/fixtures/runtime/cum.pine"),
    (
        "runtime_all_time_extremes.json",
        "tests/fixtures/runtime/all_time_extremes.pine",
    ),
    ("runtime_math.json", "tests/fixtures/runtime/math.pine"),
    (
        "runtime_math_edge_cases.json",
        "tests/fixtures/runtime/math_edge_cases.pine",
    ),
    (
        "runtime_syminfo.json",
        "tests/fixtures/runtime/syminfo.pine",
    ),
    (
        "runtime_alertcondition.json",
        "tests/fixtures/runtime/alertcondition.pine",
    ),
    ("runtime_alert.json", "tests/fixtures/runtime/alert.pine"),
    (
        "runtime_alert_frequency.json",
        "tests/fixtures/runtime/alert_frequency.pine",
    ),
    ("runtime_hline_fill.json", "tests/fixtures/runtime/io.pine"),
    (
        "runtime_label_new.json",
        "tests/fixtures/runtime/label_new.pine",
    ),
    (
        "runtime_label_options.json",
        "tests/fixtures/runtime/label_options.pine",
    ),
    (
        "runtime_label_mutation.json",
        "tests/fixtures/runtime/label_mutation.pine",
    ),
    (
        "runtime_label_control_flow.json",
        "tests/fixtures/runtime/label_control_flow.pine",
    ),
    (
        "runtime_label_delete.json",
        "tests/fixtures/runtime/label_delete.pine",
    ),
    (
        "runtime_label_copy.json",
        "tests/fixtures/runtime/label_copy.pine",
    ),
    (
        "runtime_label_getters.json",
        "tests/fixtures/runtime/label_getters.pine",
    ),
    (
        "runtime_label_xloc.json",
        "tests/fixtures/runtime/label_xloc.pine",
    ),
    (
        "runtime_label_yloc.json",
        "tests/fixtures/runtime/label_yloc.pine",
    ),
    (
        "runtime_label_array.json",
        "tests/fixtures/runtime/label_array.pine",
    ),
    (
        "runtime_line_new.json",
        "tests/fixtures/runtime/line_new.pine",
    ),
    (
        "runtime_line_mutation.json",
        "tests/fixtures/runtime/line_mutation.pine",
    ),
    (
        "runtime_line_control_flow.json",
        "tests/fixtures/runtime/line_control_flow.pine",
    ),
    (
        "runtime_line_delete.json",
        "tests/fixtures/runtime/line_delete.pine",
    ),
    (
        "runtime_line_copy.json",
        "tests/fixtures/runtime/line_copy.pine",
    ),
    (
        "runtime_line_getters.json",
        "tests/fixtures/runtime/line_getters.pine",
    ),
    (
        "runtime_line_array.json",
        "tests/fixtures/runtime/line_array.pine",
    ),
    (
        "runtime_box_new.json",
        "tests/fixtures/runtime/box_new.pine",
    ),
    (
        "runtime_box_mutation.json",
        "tests/fixtures/runtime/box_mutation.pine",
    ),
    (
        "runtime_box_control_flow.json",
        "tests/fixtures/runtime/box_control_flow.pine",
    ),
    (
        "runtime_box_delete.json",
        "tests/fixtures/runtime/box_delete.pine",
    ),
    (
        "runtime_box_copy.json",
        "tests/fixtures/runtime/box_copy.pine",
    ),
    (
        "runtime_box_getters.json",
        "tests/fixtures/runtime/box_getters.pine",
    ),
    (
        "runtime_box_array.json",
        "tests/fixtures/runtime/box_array.pine",
    ),
    (
        "runtime_drawing_methods.json",
        "tests/fixtures/runtime/drawing_methods.pine",
    ),
    (
        "runtime_table_new.json",
        "tests/fixtures/runtime/table_new.pine",
    ),
    (
        "runtime_table_array.json",
        "tests/fixtures/runtime/table_array.pine",
    ),
    (
        "runtime_table_cell.json",
        "tests/fixtures/runtime/table_cell.pine",
    ),
    (
        "runtime_table_control_flow.json",
        "tests/fixtures/runtime/table_control_flow.pine",
    ),
    (
        "runtime_table_delete.json",
        "tests/fixtures/runtime/table_delete.pine",
    ),
    (
        "runtime_table_clear.json",
        "tests/fixtures/runtime/table_clear.pine",
    ),
    (
        "runtime_table_merge_cells.json",
        "tests/fixtures/runtime/table_merge_cells.pine",
    ),
    (
        "runtime_loop_state_interactions.json",
        "tests/fixtures/runtime/loop_state_interactions.pine",
    ),
    (
        "runtime_branch_loop_interactions.json",
        "tests/fixtures/runtime/branch_loop_interactions.pine",
    ),
    ("runtime_switch.json", "tests/fixtures/runtime/switch.pine"),
    (
        "runtime_block_statements.json",
        "tests/fixtures/runtime/block_statements.pine",
    ),
    (
        "runtime_for_edges.json",
        "tests/fixtures/runtime/for_edges.pine",
    ),
    (
        "runtime_for_stateful.json",
        "tests/fixtures/runtime/for_stateful.pine",
    ),
    ("runtime_while.json", "tests/fixtures/runtime/while.pine"),
    (
        "runtime_while_edges.json",
        "tests/fixtures/runtime/while_edges.pine",
    ),
    (
        "runtime_while_stateful.json",
        "tests/fixtures/runtime/while_stateful.pine",
    ),
    (
        "runtime_local_scope.json",
        "tests/fixtures/runtime/local_scope.pine",
    ),
    (
        "runtime_history_edges.json",
        "tests/fixtures/runtime/history_edges.pine",
    ),
    (
        "runtime_dynamic_history.json",
        "tests/fixtures/runtime/dynamic_history.pine",
    ),
    (
        "runtime_dynamic_history_scopes.json",
        "tests/fixtures/runtime/dynamic_history_scopes.pine",
    ),
    (
        "runtime_series_history_offset.json",
        "tests/fixtures/runtime/series_history_offset.pine",
    ),
    (
        "runtime_max_bars_back.json",
        "tests/fixtures/runtime/max_bars_back.pine",
    ),
    (
        "runtime_varip_scalar.json",
        "tests/fixtures/runtime/varip_scalar.pine",
    ),
    (
        "runtime_varip_local.json",
        "tests/fixtures/runtime/varip_local.pine",
    ),
    (
        "runtime_varip_array.json",
        "tests/fixtures/runtime/varip_array.pine",
    ),
    (
        "runtime_request_security_same_context.json",
        "tests/fixtures/runtime/request_security_same_context.pine",
    ),
    (
        "runtime_user_types.json",
        "tests/fixtures/runtime/user_types.pine",
    ),
    (
        "runtime_user_methods.json",
        "tests/fixtures/runtime/user_methods.pine",
    ),
    (
        "runtime_strategy_empty.json",
        "tests/fixtures/runtime/strategy_no_order.pine",
    ),
    (
        "runtime_strategy_entry.json",
        "tests/fixtures/runtime/strategy_entry.pine",
    ),
    (
        "runtime_strategy_entry_limit.json",
        "tests/fixtures/runtime/strategy_entry_limit.pine",
    ),
    (
        "runtime_strategy_pyramiding_limit_same_tick_limit_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_limit_same_tick_limit_entries.pine",
    ),
    (
        "runtime_strategy_limit_verification_entry.json",
        "tests/fixtures/runtime/strategy_limit_verification_entry.pine",
    ),
    (
        "runtime_strategy_entry_stop.json",
        "tests/fixtures/runtime/strategy_entry_stop.pine",
    ),
    (
        "runtime_strategy_pyramiding_limit_same_tick_stop_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_limit_same_tick_stop_entries.pine",
    ),
    (
        "runtime_strategy_entry_stop_limit.json",
        "tests/fixtures/runtime/strategy_entry_stop_limit.pine",
    ),
    (
        "runtime_strategy_pyramiding_limit_same_tick_stop_limit_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_limit_same_tick_stop_limit_entries.pine",
    ),
    (
        "runtime_strategy_default_quantity.json",
        "tests/fixtures/runtime/strategy_default_quantity.pine",
    ),
    (
        "runtime_strategy_builtin_default_quantity.json",
        "tests/fixtures/runtime/strategy_builtin_default_quantity.pine",
    ),
    (
        "runtime_strategy_percent_of_equity_default_quantity.json",
        "tests/fixtures/runtime/strategy_percent_of_equity_default_quantity.pine",
    ),
    (
        "runtime_strategy_cash_default_quantity.json",
        "tests/fixtures/runtime/strategy_cash_default_quantity.pine",
    ),
    (
        "runtime_strategy_cash_default_quantity_limit.json",
        "tests/fixtures/runtime/strategy_cash_default_quantity_limit.pine",
    ),
    (
        "runtime_strategy_cash_default_quantity_override.json",
        "tests/fixtures/runtime/strategy_cash_default_quantity_override.pine",
    ),
    (
        "runtime_strategy_default_quantity_override.json",
        "tests/fixtures/runtime/strategy_default_quantity_override.pine",
    ),
    (
        "runtime_strategy_close.json",
        "tests/fixtures/runtime/strategy_close.pine",
    ),
    (
        "runtime_strategy_close_qty_partial.json",
        "tests/fixtures/runtime/strategy_close_qty_partial.pine",
    ),
    (
        "runtime_strategy_close_qty_full_clamp.json",
        "tests/fixtures/runtime/strategy_close_qty_full_clamp.pine",
    ),
    (
        "runtime_strategy_close_qty_percent_precedence.json",
        "tests/fixtures/runtime/strategy_close_qty_percent_precedence.pine",
    ),
    (
        "runtime_strategy_close_all.json",
        "tests/fixtures/runtime/strategy_close_all.pine",
    ),
    (
        "runtime_strategy_cancel_entry.json",
        "tests/fixtures/runtime/strategy_cancel_entry.pine",
    ),
    (
        "runtime_strategy_cancel_all_entry_exit.json",
        "tests/fixtures/runtime/strategy_cancel_all_entry_exit.pine",
    ),
    (
        "runtime_strategy_exit_stop.json",
        "tests/fixtures/runtime/strategy_exit_stop.pine",
    ),
    (
        "runtime_strategy_exit_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_limit_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_limit_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_profit_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_profit_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_loss_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_loss_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_bracket_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_bracket_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_stop_profit_bracket_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_stop_profit_bracket_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_loss_limit_bracket_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_loss_limit_bracket_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_loss_profit_bracket_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_loss_profit_bracket_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_bracket_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_bracket_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_stop_profit_bracket_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_stop_profit_bracket_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_loss_limit_bracket_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_loss_limit_bracket_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_loss_profit_bracket_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_loss_profit_bracket_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_limit_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_limit_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_profit_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_profit_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_loss_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_loss_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_trailing_while_flat_noop.json",
        "tests/fixtures/runtime/strategy_exit_trailing_while_flat_noop.pine",
    ),
    (
        "runtime_strategy_exit_trailing_unmatched_from_entry_noop.json",
        "tests/fixtures/runtime/strategy_exit_trailing_unmatched_from_entry_noop.pine",
    ),
    (
        "runtime_strategy_exit_limit.json",
        "tests/fixtures/runtime/strategy_exit_limit.pine",
    ),
    (
        "runtime_strategy_exit_profit.json",
        "tests/fixtures/runtime/strategy_exit_profit.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_attachment.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_attachment.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_profit_attachment.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_profit_attachment.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_loss_attachment.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_loss_attachment.pine",
    ),
    (
        "runtime_strategy_exit_loss.json",
        "tests/fixtures/runtime/strategy_exit_loss.pine",
    ),
    (
        "runtime_strategy_exit_interactions.json",
        "tests/fixtures/runtime/strategy_exit_interactions.pine",
    ),
    (
        "runtime_strategy_exit_profit_loss_interactions.json",
        "tests/fixtures/runtime/strategy_exit_profit_loss_interactions.pine",
    ),
    (
        "runtime_strategy_exit_bracket_stop_limit_limit_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_stop_limit_limit_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_stop_limit_stop_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_stop_limit_stop_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_loss_profit_profit_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_loss_profit_profit_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_loss_profit_loss_fill.json",
        "tests/fixtures/runtime/strategy_exit_bracket_loss_profit_loss_fill.pine",
    ),
    (
        "runtime_strategy_exit_bracket_mixed_pairs.json",
        "tests/fixtures/runtime/strategy_exit_bracket_mixed_pairs.pine",
    ),
    (
        "runtime_strategy_exit_bracket_creation_bar.json",
        "tests/fixtures/runtime/strategy_exit_bracket_creation_bar.pine",
    ),
    (
        "runtime_strategy_exit_bracket_repeated.json",
        "tests/fixtures/runtime/strategy_exit_bracket_repeated.pine",
    ),
    (
        "runtime_strategy_exit_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_omitted_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_omitted_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_bracket_invalid_leg.json",
        "tests/fixtures/runtime/strategy_exit_bracket_invalid_leg.pine",
    ),
    (
        "runtime_strategy_exit_bracket_both_hit.json",
        "tests/fixtures/runtime/strategy_exit_bracket_both_hit.pine",
    ),
    (
        "runtime_strategy_exit_bracket_state.json",
        "tests/fixtures/runtime/strategy_exit_bracket_state.pine",
    ),
    (
        "runtime_strategy_exit_bracket_interactions.json",
        "tests/fixtures/runtime/strategy_exit_bracket_interactions.pine",
    ),
    (
        "runtime_strategy_exit_trail_price_fill.json",
        "tests/fixtures/runtime/strategy_exit_trail_price_fill.pine",
    ),
    (
        "runtime_strategy_exit_trail_points_fill.json",
        "tests/fixtures/runtime/strategy_exit_trail_points_fill.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_trail_points_attachment.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_trail_points_attachment.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_stop_profit_bracket.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_stop_profit_bracket.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_loss_limit_bracket.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_loss_limit_bracket.pine",
    ),
    (
        "runtime_strategy_exit_active_entry_loss_profit_bracket.json",
        "tests/fixtures/runtime/strategy_exit_active_entry_loss_profit_bracket.pine",
    ),
    (
        "runtime_strategy_exit_trailing_activation_bar.json",
        "tests/fixtures/runtime/strategy_exit_trailing_activation_bar.pine",
    ),
    (
        "runtime_strategy_exit_trailing_ratchet.json",
        "tests/fixtures/runtime/strategy_exit_trailing_ratchet.pine",
    ),
    (
        "runtime_strategy_exit_trailing_repeated.json",
        "tests/fixtures/runtime/strategy_exit_trailing_repeated.pine",
    ),
    (
        "runtime_strategy_exit_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_omitted_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_omitted_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_trailing_invalid.json",
        "tests/fixtures/runtime/strategy_exit_trailing_invalid.pine",
    ),
    (
        "runtime_strategy_exit_trailing_close_cancel.json",
        "tests/fixtures/runtime/strategy_exit_trailing_close_cancel.pine",
    ),
    (
        "runtime_strategy_exit_trailing_interactions.json",
        "tests/fixtures/runtime/strategy_exit_trailing_interactions.pine",
    ),
    (
        "runtime_strategy_exit_trailing_state.json",
        "tests/fixtures/runtime/strategy_exit_trailing_state.pine",
    ),
    (
        "runtime_strategy_exit_qty_stop_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_stop_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_limit_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_limit_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_bracket_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_bracket_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_trailing_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_trailing_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_full_clamp.json",
        "tests/fixtures/runtime/strategy_exit_qty_full_clamp.pine",
    ),
    (
        "runtime_strategy_exit_qty_repeated.json",
        "tests/fixtures/runtime/strategy_exit_qty_repeated.pine",
    ),
    (
        "runtime_strategy_exit_qty_replacement.json",
        "tests/fixtures/runtime/strategy_exit_qty_replacement.pine",
    ),
    (
        "runtime_strategy_exit_qty_state.json",
        "tests/fixtures/runtime/strategy_exit_qty_state.pine",
    ),
    (
        "runtime_strategy_exit_qty_precedence_stop.json",
        "tests/fixtures/runtime/strategy_exit_qty_precedence_stop.pine",
    ),
    (
        "runtime_strategy_exit_qty_precedence_bracket.json",
        "tests/fixtures/runtime/strategy_exit_qty_precedence_bracket.pine",
    ),
    (
        "runtime_strategy_exit_qty_precedence_trailing.json",
        "tests/fixtures/runtime/strategy_exit_qty_precedence_trailing.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_stop_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_stop_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_limit_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_limit_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_stop_limit_downside_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_stop_limit_downside_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_stop_limit_upside_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_stop_limit_upside_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_bracket_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_bracket_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_bracket_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_bracket_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_mixed_bracket_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_mixed_bracket_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_bracket_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_bracket_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_bracket_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_bracket_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_single_downside_precedence.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_single_downside_precedence.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_single_upside_order.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_single_upside_order.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_single_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_single_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_state.pine",
    ),
    (
        "runtime_strategy_exit_reservation_bracket_host_parity.json",
        "tests/fixtures/runtime/strategy_exit_reservation_bracket_host_parity.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_price_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_price_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_points_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_points_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_trailing_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_trailing_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_state.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_trailing_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_trailing_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_mixed_trailing_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_mixed_trailing_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_trailing_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_trailing_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_trailing_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_trailing_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_host_parity.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_host_parity.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_single_downside_order.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_single_downside_order.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_bracket_downside_order.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_bracket_downside_order.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_mixed_side_precedence.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_mixed_side_precedence.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_activation_mixed_fill.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_activation_mixed_fill.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_replacement_mixed.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_replacement_mixed.pine",
    ),
    (
        "runtime_strategy_exit_reservation_trailing_mixed_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_trailing_mixed_state.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_stop_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_stop_partial.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_stop_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_stop_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_mixed_stop_multi.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_mixed_stop_multi.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_replacement.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_replacement.pine",
    ),
    (
        "runtime_strategy_exit_reservation_qty_percent_clamp.json",
        "tests/fixtures/runtime/strategy_exit_reservation_qty_percent_clamp.pine",
    ),
    (
        "runtime_strategy_exit_reservation_mixed_side_precedence.json",
        "tests/fixtures/runtime/strategy_exit_reservation_mixed_side_precedence.pine",
    ),
    (
        "runtime_strategy_exit_reservation_state.json",
        "tests/fixtures/runtime/strategy_exit_reservation_state.pine",
    ),
    (
        "runtime_strategy_exit_reservation_interactions.json",
        "tests/fixtures/runtime/strategy_exit_reservation_interactions.pine",
    ),
    (
        "runtime_strategy_exit_omitted_single_replacement.json",
        "tests/fixtures/runtime/strategy_exit_omitted_single_replacement.pine",
    ),
    (
        "runtime_strategy_exit_omitted_replaces_reservations.json",
        "tests/fixtures/runtime/strategy_exit_omitted_replaces_reservations.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_limit_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_limit_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_bracket_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_bracket_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_trailing_partial.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_trailing_partial.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_full.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_full.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_full_clamp.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_full_clamp.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_repeated.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_repeated.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_replacement.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_replacement.pine",
    ),
    (
        "runtime_strategy_exit_qty_percent_state.json",
        "tests/fixtures/runtime/strategy_exit_qty_percent_state.pine",
    ),
    (
        "runtime_strategy_equity.json",
        "tests/fixtures/runtime/strategy_equity.pine",
    ),
    (
        "runtime_strategy_commission_cash_per_contract.json",
        "tests/fixtures/runtime/strategy_commission_cash_per_contract.pine",
    ),
    (
        "runtime_strategy_commission_cash_per_order.json",
        "tests/fixtures/runtime/strategy_commission_cash_per_order.pine",
    ),
    (
        "runtime_strategy_commission_percent.json",
        "tests/fixtures/runtime/strategy_commission_percent.pine",
    ),
    (
        "runtime_strategy_slippage.json",
        "tests/fixtures/runtime/strategy_slippage.pine",
    ),
    (
        "runtime_strategy_exit_slippage.json",
        "tests/fixtures/runtime/strategy_exit_slippage.pine",
    ),
    (
        "runtime_strategy_limit_verification_exit.json",
        "tests/fixtures/runtime/strategy_limit_verification_exit.pine",
    ),
    (
        "runtime_strategy_position_state.json",
        "tests/fixtures/runtime/strategy_position_state.pine",
    ),
    (
        "runtime_strategy_profit_state.json",
        "tests/fixtures/runtime/strategy_profit_state.pine",
    ),
    (
        "runtime_strategy_profit_percent_state.json",
        "tests/fixtures/runtime/strategy_profit_percent_state.pine",
    ),
    (
        "runtime_strategy_variable_interactions.json",
        "tests/fixtures/runtime/strategy_variable_interactions.pine",
    ),
    (
        "runtime_strategy_trade_counts.json",
        "tests/fixtures/runtime/strategy_trade_counts.pine",
    ),
    (
        "runtime_strategy_closedtrades_fields.json",
        "tests/fixtures/runtime/strategy_closedtrades_fields.pine",
    ),
    (
        "runtime_strategy_opentrades_fields.json",
        "tests/fixtures/runtime/strategy_opentrades_fields.pine",
    ),
    (
        "runtime_strategy_pyramiding.json",
        "tests/fixtures/runtime/strategy_pyramiding.pine",
    ),
    (
        "runtime_strategy_pyramiding_close.json",
        "tests/fixtures/runtime/strategy_pyramiding_close.pine",
    ),
    (
        "runtime_strategy_pyramiding_close_all.json",
        "tests/fixtures/runtime/strategy_pyramiding_close_all.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_profit_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_profit_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_bracket_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_bracket_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_trail_points_from_entry.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_trail_points_from_entry.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_from_entry_current.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_from_entry_current.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_from_entry_persistent.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_from_entry_persistent.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_profit_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_profit_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_profit_same_id.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_profit_same_id.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_profit_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_profit_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_same_id.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_same_id.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_profit_bracket_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_profit_bracket_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_profit_bracket_same_id.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_profit_bracket_same_id.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_profit_bracket_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_profit_bracket_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_stop_profit_bracket_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_stop_profit_bracket_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_stop_profit_bracket_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_stop_profit_bracket_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_limit_bracket_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_limit_bracket_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_loss_limit_bracket_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_loss_limit_bracket_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_stop_limit_bracket_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_stop_limit_bracket_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_stop_limit_bracket_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_stop_limit_bracket_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_trail_price_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_trail_price_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_trail_price_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_trail_price_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_trail_points_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_trail_points_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_omitted_trail_points_persistent_from_entries.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_omitted_trail_points_persistent_from_entries.pine",
    ),
    (
        "runtime_strategy_pyramiding_exit_same_id.json",
        "tests/fixtures/runtime/strategy_pyramiding_exit_same_id.pine",
    ),
    (
        "runtime_strategy_margin_capital_held_long.json",
        "tests/fixtures/runtime/strategy_margin_capital_held_long.pine",
    ),
    (
        "runtime_strategy_margin_entry_affordability.json",
        "tests/fixtures/runtime/strategy_margin_entry_affordability_long.pine",
    ),
    (
        "runtime_strategy_margin_call_long.json",
        "tests/fixtures/runtime/strategy_margin_call_long.pine",
    ),
    (
        "runtime_strategy_trade_outcome_counts.json",
        "tests/fixtures/runtime/strategy_trade_outcome_counts.pine",
    ),
    (
        "runtime_strategy_exit_trade_counts.json",
        "tests/fixtures/runtime/strategy_exit_trade_counts.pine",
    ),
];

pub(crate) type RuntimeLibrarySnapshotFixture = (
    &'static str,
    &'static str,
    &'static [(&'static str, &'static str)],
);

pub(crate) const RUNTIME_LIBRARY_SNAPSHOT_FIXTURES: &[RuntimeLibrarySnapshotFixture] = &[
    (
        "runtime_import.json",
        "tests/fixtures/runtime/import.pine",
        &[("user/lib/1", "tests/fixtures/libraries/import_lib.pine")],
    ),
    (
        "runtime_import_state.json",
        "tests/fixtures/runtime/import_state.pine",
        &[("user/lib/1", "tests/fixtures/libraries/import_lib.pine")],
    ),
];
