//@version=5
indicator("Block statements")
sum = 0
if close > open
    sum := sum + 1
else
    sum := sum + 2
for i = 0 to 5 by 2
    if i == 2
        continue
    if i == 4
        break
    sum := sum + i
last = for j = 0 to 5
    if j == 2
        continue
    if j == 4
        break
    j * 2
[left, right] = for k = 0 to 3
    if k == 1
        continue
    if k == 3
        break
    [k, k * 2]
plot(close + sum + last + left + right)
