//@version=5
indicator("Box control flow")
var box_id = box.new(bar_index, high, bar_index, low)
if bar_index == 1
    box.set_left(box_id, bar_index)
    box.set_top(box_id, close + 10)
    box.set_right(box_id, bar_index + 2)
    box.set_bottom(box_id, close - 10)
    box.set_lefttop(box_id, bar_index + 1, close + 20)
    box.set_rightbottom(box_id, bar_index + 4, close - 20)
direction = close > open ? 1 : -1
switch direction
    1 => box.set_bgcolor(box_id, color.green)
    => box.set_bgcolor(box_id, color.red)
switch direction
    1 => box.set_border_color(box_id, color.white)
    => box.set_border_color(box_id, color.black)
for i = 0 to 0
    if bar_index == 2
        box.set_border_width(box_id, 2)
j = 0
while j < 1
    if bar_index == 3
        box.set_border_style(box_id, line.style_dashed)
        box.set_extend(box_id, extend.right)
        box.set_xloc(box_id, bar_index - 2, bar_index + 3, xloc.bar_index)
        box.set_text(box_id, "flow box")
        box.set_text_color(box_id, color.white)
        box.set_text_size(box_id, size.small)
        box.set_text_halign(box_id, text.align_left)
        box.set_text_valign(box_id, text.align_top)
        box.set_text_wrap(box_id, text.wrap_auto)
    j := j + 1
plot(close)
