//@version=5
indicator("Box control flow")
var box_id = box.new(bar_index, high, bar_index, low)
if bar_index == 1
    box.set_left(box_id, bar_index)
    box.set_top(box_id, close + 10)
    box.set_right(box_id, bar_index + 2)
    box.set_bottom(box_id, close - 10)
    box.set_lefttop(box_id, bar_index + 1, close + 20)
    box.set_rightbottom(box_id, bar_index + 4, close - 20)
direction = close > open ? 1 : -1
switch direction
    1 => box.set_bgcolor(box_id, color.green)
    => box.set_bgcolor(box_id, color.red)
for i = 0 to 0
    if bar_index == 2
        box.set_border_width(box_id, 2)
j = 0
while j < 1
    if bar_index == 3
        box.set_border_style(box_id, line.style_dashed)
    j := j + 1
plot(close)
