//@version=5
indicator("Box mutation")
var box_id = box.new(bar_index, high, bar_index, low)
if bar_index == 1
    box.set_lefttop(box_id, bar_index, open)
if bar_index == 2
    box.set_rightbottom(box_id, bar_index, close)
    box.set_xloc(box_id, bar_index - 1, bar_index + 1, xloc.bar_index)
    box.set_bgcolor(box_id, color.green)
for i = 0 to 0
    if bar_index == 3
        box.set_border_color(box_id, color.white)
        box.set_border_width(box_id, 2)
        box.set_border_style(box_id, line.style_dashed)
        box.set_extend(box_id, extend.right)
        box.set_extend(box_id, extend.left)
        box.set_extend(box_id, extend.both)
        box.set_extend(box_id, extend.none)
        box.set_text(box_id, "box text")
        box.set_text_color(box_id, color.white)
        box.set_text_size(box_id, 19)
        box.set_text_halign(box_id, text.align_left)
        box.set_text_valign(box_id, text.align_top)
        box.set_text_wrap(box_id, text.wrap_auto)
        box.set_text_font_family(box_id, font.family_monospace)
        box.set_text_formatting(box_id, text.format_bold + text.format_italic)
box.set_xloc(na, bar_index, bar_index + 1, xloc.bar_index)
box.set_text_formatting(na, text.format_italic)
plot(close)
