//@version=5
indicator("Box delete")
var box_id = box.new(bar_index, high, bar_index, low)
var loop_box = box.new(bar_index, high + 1, bar_index, low - 1)
if bar_index == 1
    box.delete(box_id)
if bar_index == 2
    box.set_bgcolor(box_id, color.green)
    box.delete(box_id)
if bar_index == 3
    delete_i = 0
    while delete_i < 1
        box.delete(loop_box)
        delete_i := delete_i + 1
box.delete(na)
plot(close)
