//@version=5
indicator("For in line array")

first = line.new(bar_index, high, bar_index + 1, low)
second = line.new(bar_index + 2, high + 1, bar_index + 3, low + 1)
lines = array.from(first, second)

int x_sum = 0
float y_sum = 0.0
for id in lines
    line.set_x1(id, line.get_x1(id) + 10)
    line.set_y1(id, line.get_y1(id) + 1)
    x_sum := x_sum + line.get_x1(id)
    y_sum := y_sum + line.get_y1(id)

first_after = lines.get(0)
plot(x_sum)
plot(y_sum)
plot(line.get_x1(first_after))
