//@version=5
indicator("For in index value linefill")

upper = line.new(10, high, 11, high + 1)
middle = line.new(12, close, 13, close + 1)
lower = line.new(14, low, 15, low - 1)
first = linefill.new(upper, middle, color.green)
second = linefill.new(middle, lower, color.red)
fills = array.from(first, second)

int index_sum = 0
int x_sum = 0
for index, value in fills
    index_sum := index_sum + index
    linefill.set_color(value, index == 0 ? color.blue : color.yellow)
    x_sum := x_sum + line.get_x1(linefill.get_line1(value))
    x_sum := x_sum + line.get_x2(linefill.get_line2(value))

first_after = fills.get(0)
second_after = fills.get(1)

plot(index_sum)
plot(x_sum)
plot(line.get_x1(linefill.get_line1(first_after)))
plot(line.get_x2(linefill.get_line2(second_after)))
