//@version=5
indicator("For in linefill array")

upper = line.new(bar_index, high, bar_index + 1, high + 1)
middle = line.new(bar_index + 2, close, bar_index + 3, close + 1)
lower = line.new(bar_index + 4, low, bar_index + 5, low - 1)
first = linefill.new(upper, middle, color.green)
second = linefill.new(middle, lower, color.red)
fills = array.from(first, second)

int x_sum = 0
for id in fills
    linefill.set_color(id, color.blue)
    x_sum := x_sum + line.get_x1(linefill.get_line1(id))
    x_sum := x_sum + line.get_x2(linefill.get_line2(id))

first_after = fills.get(0)
linefill.set_color(first_after, color.yellow)
plot(x_sum)
plot(line.get_x1(linefill.get_line1(first_after)))
