//@version=5
indicator("For in index value UDT array")

type Point
    float x
    string tag

points = array.from(Point.new(close, "close"), Point.new(open, "open"), Point.new(high, "high"))

float sum = 0.0
int loop_index_sum = 0
int tag_len = 0
for index, point in points
    point.x := point.x + 10
    loop_index_sum := loop_index_sum + index
    sum := sum + point.x
    tag_len := tag_len + str.length(point.tag)

first_after = points.get(0)
second_after = points.get(1)
plot(loop_index_sum)
plot(sum)
plot(tag_len)
plot(first_after.x)
plot(second_after.x)
