//@version=5
indicator("For edges")
limit = close > 1 ? 3 : na
sum = close > 0 ? 0 : 0
for i = 0 to limit by -2
    if close < 3 and i == 2
        continue
    sum := sum + i
loop_value = for j = close > 2 ? 3 : na to 0 by 2
    if j == 1
        continue
    j
nested_loop_value = for outer = 0 to 0
    for inner = 0 to 0
        close + 5
plot(close + sum + nz(loop_value))
plot(nested_loop_value)
