//@version=5
indicator("Label mutation")
var label_id = label.new(bar_index, high, "start")
if bar_index == 0
    label.set_text(label_id, "same-bar")
if bar_index == 1
    label.set_xy(label_id, bar_index, close)
if close > 2
    label.set_color(label_id, color.green)
for i = 0 to 0
    if bar_index == 3
        label.set_tooltip(label_id, "loop")
        label.set_textalign(label_id, text.align_left)
        label.set_text_font_family(label_id, font.family_monospace)
        label.set_text_formatting(label_id, text.format_bold + text.format_italic)
label.set_text_formatting(na, text.format_italic)
plot(close)
