//@version=5
indicator("Label delete")
var label_id = label.new(bar_index, high, "start")
var loop_label = label.new(bar_index, low, "loop")
if bar_index == 1
    label.delete(label_id)
if bar_index == 2
    label.set_text(label_id, "ignored")
    label.delete(label_id)
if bar_index == 3
    delete_i = 0
    while delete_i < 1
        label.delete(loop_label)
        delete_i := delete_i + 1
label.delete(na)
plot(close)
