//@version=5
indicator("Label xloc")
var label_id = label.new(bar_index, high, "start")
var independent_label = label.new(bar_index, low, "independent")
if bar_index == 1
    label.set_xloc(label_id, time, xloc.bar_time)
if bar_index == 2
    label.set_xloc(label_id, bar_index, xloc.bar_index)
if bar_index == 3
    xloc_i = 0
    while xloc_i < 1
        label.set_xloc(label_id, bar_index + 10, xloc.bar_index)
        xloc_i := xloc_i + 1
independent_xloc_i = 0
while independent_xloc_i < 1
    if bar_index == 3
        label.set_xloc(independent_label, bar_index + 20, xloc.bar_index)
    independent_xloc_i := independent_xloc_i + 1
if bar_index == 3
    label.set_xloc(na, bar_index, xloc.bar_index)
plot(close)
