//@version=5
indicator("Label control flow")
var label_id = label.new(bar_index, high, "start")
if bar_index == 1
    label.set_x(label_id, bar_index)
    label.set_y(label_id, low)
    label.set_xy(label_id, bar_index + 1, close)
    label.set_text(label_id, "if")
direction = close > open ? 1 : -1
switch direction
    1 => label.set_color(label_id, color.green)
    => label.set_color(label_id, color.red)
for i = 0 to 0
    if bar_index == 2
        label.set_tooltip(label_id, "for")
j = 0
while j < 1
    if bar_index == 3
        label.set_size(label_id, size.small)
    j := j + 1
plot(close)
