//@version=5
indicator("Label yloc")
var label_id = label.new(bar_index, high, "start")
var independent_label = label.new(bar_index, low, "independent")
if bar_index == 1
    label.set_yloc(label_id, yloc.abovebar)
if bar_index == 2
    label.set_yloc(label_id, yloc.belowbar)
if bar_index == 3
    yloc_i = 0
    while yloc_i < 1
        label.set_yloc(label_id, yloc.price)
        yloc_i := yloc_i + 1
independent_yloc_i = 0
while independent_yloc_i < 1
    if bar_index == 3
        label.set_yloc(independent_label, yloc.abovebar)
    independent_yloc_i := independent_yloc_i + 1
if bar_index == 3
    label.set_yloc(na, yloc.price)
plot(close)
