//@version=5
indicator("Line delete")
var line_id = line.new(bar_index, high, bar_index, low)
var loop_line = line.new(bar_index, high + 1, bar_index, low - 1)
if bar_index == 1
    line.delete(line_id)
if bar_index == 3
    delete_i = 0
    while delete_i < 1
        line.delete(loop_line)
        delete_i := delete_i + 1
if bar_index == 2
    line.set_color(line_id, color.green)
    line.delete(line_id)
line.delete(na)
plot(close)
