//@version=5
indicator("Linefill set color")
var upper = line.new(bar_index, high, bar_index + 1, high + 1, color=color.green)
var lower = line.new(bar_index, low, bar_index + 1, low - 1, color=color.red)
var channel = linefill.new(upper, lower, color.green)
if bar_index == 1
    linefill.set_color(channel, color.red)
if bar_index == 2
    replacement = linefill.new(upper, lower, color.blue)
    linefill.set_color(channel, color.yellow)
    linefill.set_color(replacement, color.new(color.green, 80))
if bar_index == 3
    linefill.set_color(na, color.red)
plot(close)
