//@version=5
indicator("Linefill new")
var upper = line.new(bar_index, high, bar_index + 1, high + 1, color=color.green)
var lower = line.new(bar_index, low, bar_index + 1, low - 1, color=color.red)
var other = line.new(bar_index, close, bar_index + 1, close)
if bar_index == 1
    first = linefill.new(upper, lower, color.new(color.green, 80))
if bar_index == 2
    replacement = linefill.new(upper, lower, color.new(color.red, 70))
    second = linefill.new(lower, other, color.blue)
if bar_index == 3
    again = linefill.new(upper, lower, color.yellow)
    missing = linefill.new(na, other, color.yellow)
plot(close)
