//@version=5
indicator("Line control flow")
var line_id = line.new(bar_index, high, bar_index, low)
if bar_index == 1
    line.set_x1(line_id, bar_index + 1)
    line.set_y1(line_id, close + 10)
    line.set_color(line_id, color.green)
direction = close > open ? 1 : -1
switch direction
    1 => line.set_style(line_id, line.style_dashed)
    => line.set_style(line_id, line.style_dotted)
for i = 0 to 0
    if bar_index == 2
        line.set_width(line_id, 2)
j = 0
while j < 1
    if bar_index == 3
        line.set_extend(line_id, extend.right)
    j := j + 1
plot(close)
