//@version=5
indicator("Line mutation")
var line_id = line.new(bar_index, high, bar_index, low)
if bar_index == 1
    line.set_xy1(line_id, bar_index, open)
if bar_index == 2
    line.set_xy2(line_id, bar_index, close)
    line.set_color(line_id, color.green)
for i = 0 to 0
    if bar_index == 3
        line.set_width(line_id, 2)
        line.set_style(line_id, line.style_dashed)
        line.set_style(line_id, line.style_arrow_left)
        line.set_style(line_id, line.style_arrow_right)
        line.set_style(line_id, line.style_arrow_both)
        line.set_extend(line_id, extend.right)
        line.set_extend(line_id, extend.left)
        line.set_extend(line_id, extend.both)
        line.set_extend(line_id, extend.none)
        line.set_xloc(line_id, bar_index - 2, bar_index + 2, xloc.bar_index)
line.set_xloc(na, bar_index, bar_index, xloc.bar_index)
plot(close)
