//@version=5
indicator("Line copy")
var original = line.new(bar_index - 1, low, bar_index, high)
var copy = line.copy(original)
if bar_index == 1
    line.set_color(original, color.green)
    line.set_xy1(copy, bar_index, low)
    line.set_xy2(copy, bar_index + 1, high)
    copy_i = 0
    while copy_i < 1
        line.copy(original)
        copy_i := copy_i + 1
if bar_index == 2
    line.delete(copy)
    line.copy(copy)
line.copy(na)
plot(close)
