//@version=5
indicator("Line control flow")
var line_id = line.new(bar_index, high, bar_index, low)
if bar_index == 1
    line.set_x1(line_id, bar_index + 1)
    line.set_y1(line_id, close + 10)
xy1_i = 0
while xy1_i < 1
    if bar_index == 1
        line.set_xy1(line_id, bar_index + 2, close + 20)
    xy1_i := xy1_i + 1
x2_i = 0
while x2_i < 1
    if bar_index == 1
        line.set_x2(line_id, bar_index + 3)
    x2_i := x2_i + 1
y2_i = 0
while y2_i < 1
    if bar_index == 1
        line.set_y2(line_id, close + 30)
    y2_i := y2_i + 1
xy2_i = 0
while xy2_i < 1
    if bar_index == 1
        line.set_xy2(line_id, bar_index + 4, close + 40)
    xy2_i := xy2_i + 1
color_i = 0
while color_i < 1
    if bar_index == 1
        line.set_color(line_id, color.green)
    color_i := color_i + 1
direction = close > open ? 1 : -1
style_i = 0
while style_i < 1
    if direction == 1
        line.set_style(line_id, line.style_dashed)
    else
        line.set_style(line_id, line.style_dotted)
    style_i := style_i + 1
width_i = 0
while width_i < 1
    if bar_index == 2
        line.set_width(line_id, 2)
    width_i := width_i + 1
j = 0
while j < 1
    if bar_index == 3
        line.set_extend(line_id, extend.right)
        line.set_xloc(line_id, bar_index - 2, bar_index + 3, xloc.bar_index)
    j := j + 1
plot(close)
