//@version=5
strategy("Trade outcome counts")

if bar_index == 0
    strategy.entry("W", strategy.long, qty=1)

if bar_index == 2
    strategy.close("W")

if bar_index == 3
    strategy.entry("L", strategy.long, qty=1)

if bar_index == 5
    strategy.close("L")

if bar_index == 6
    strategy.entry("E", strategy.long, qty=1)

if bar_index == 8
    strategy.close("E")

plot(strategy.wintrades)
plot(strategy.losstrades)
plot(strategy.eventrades)
plot(strategy.closedtrades)
plot(strategy.grossprofit)
plot(strategy.grossloss)
plot(strategy.avg_trade)
