//@version=5
strategy("Margin capital held long", margin_long=50)
if bar_index == 0
    strategy.entry("L", strategy.long, qty=2)
if bar_index == 3
    strategy.close("L")
plot(strategy.opentrades.capital_held)
independent_capital_held = strategy.opentrades.capital_held * 0
capital_held_i = 0
while capital_held_i < 1
    independent_capital_held := strategy.opentrades.capital_held
    capital_held_i := capital_held_i + 1
plot(independent_capital_held)
