//@version=5
strategy("Close entries rule FIFO close all", pyramiding=2, close_entries_rule="FIFO")

if bar_index == 0
    strategy.entry("L1", strategy.long, qty=1)
if bar_index == 1
    strategy.entry("L2", strategy.long, qty=3)
if bar_index == 2
    strategy.close_all()

plot(strategy.closedtrades)
plot(strategy.closedtrades.entry_id(0) == "L1" ? 1 : 0)
plot(strategy.closedtrades.entry_id(1) == "L2" ? 1 : 0)
