//@version=5
strategy("Strategy profit state", initial_capital=1000)
plot(strategy.openprofit)
plot(strategy.netprofit)
plot(strategy.equity)
plot(strategy.max_runup)
plot(strategy.max_runup_percent)
plot(strategy.max_drawdown)
plot(strategy.max_drawdown_percent)
if bar_index == 1
    strategy.entry("L", strategy.long, qty=2)
if bar_index == 3
    strategy.close("L")
if bar_index == 4
    strategy.entry("L2", strategy.long, qty=1)
if bar_index == 5
    strategy.close("L2")
plot(strategy.openprofit)
plot(strategy.netprofit)
plot(strategy.equity)
plot(strategy.max_runup)
plot(strategy.max_runup_percent)
plot(strategy.max_drawdown)
plot(strategy.max_drawdown_percent)
