//@version=5
strategy("Bracket interactions")

adjust(value) =>
    value

stop_price = switch bar_index
    0 => adjust(0.5)
    => adjust(0.5)

limit_price = high[0] + 1.5

if bar_index == 0
    for i = 0 to 0
        j = 0
        while j < 1
            strategy.entry("L", strategy.long, qty=2)
            strategy.exit("XB", "L", stop=stop_price, limit=limit_price)
            j := j + 1

plot(strategy.position_size)
plot(strategy.position_size[1])
