//@version=5
strategy("Strategy profit percent state", initial_capital=1000)

if bar_index == 0
    strategy.entry("W", strategy.long, qty=1)

if bar_index == 2
    strategy.close("W")

if bar_index == 3
    strategy.entry("L", strategy.long, qty=1)

if bar_index == 5
    strategy.close("L")

plot(strategy.netprofit)
plot(strategy.netprofit_percent)
plot(strategy.grossprofit)
plot(strategy.grossprofit_percent)
plot(strategy.grossloss)
plot(strategy.grossloss_percent)
