//@version=5
strategy("Exit interactions")

limit_price = switch bar_index
    0 => 2.5
    => 10.0

before_size = strategy.position_size

if bar_index == 0
    for i = 0 to 0
        strategy.entry("L", strategy.long, qty=1)
    j = 0
    while j < 1
        strategy.exit("XL", "L", limit=limit_price)
        j := j + 1

after_size = strategy.position_size

plot(before_size)
plot(after_size)
plot(strategy.position_size)
plot(strategy.position_size[1])
plot(strategy.netprofit)
