//@version=5
strategy("Margin entry affordability short", initial_capital=4, margin_short=100)
if bar_index == 0
    strategy.entry("too-big-market", strategy.short, qty=3)
if bar_index == 1
    strategy.entry("too-big-stop", strategy.short, qty=2, stop=3)
if bar_index == 2
    strategy.entry("covered-market", strategy.short, qty=1)
plot(strategy.position_size)
plot(strategy.opentrades.capital_held)
