//@version=5
strategy("Bracket replacement")
if bar_index == 0
    strategy.entry("L1", strategy.long, qty=1)
    strategy.exit("XB1", "L1", stop=0.5, limit=2)
if bar_index == 1
    strategy.exit("XB1", "L1", stop=0.5, limit=2.5)
if bar_index == 3
    strategy.entry("L2", strategy.long, qty=1)
    strategy.exit("XS", "L2", limit=6)
if bar_index == 4
    strategy.exit("XB2", "L2", stop=4, limit=6.5)
if bar_index == 6
    strategy.entry("L3", strategy.long, qty=1)
    strategy.exit("XB3", "L3", stop=8, limit=10)
if bar_index == 7
    strategy.exit("XL", "L3", limit=10.5)
plot(strategy.position_size)
plot(strategy.netprofit)
