//@version=5
strategy("Close entries rule ANY exit from entry", pyramiding=2, close_entries_rule="ANY")

if bar_index == 0
    strategy.entry("older", strategy.long, qty=1)
if bar_index == 1
    strategy.entry("target", strategy.long, qty=2)
if bar_index == 2
    strategy.exit("XT", from_entry="target", limit=5)

plot(strategy.closedtrades)
plot(strategy.closedtrades.entry_id(0) == "target" ? 1 : 0)
plot(strategy.position_size)
