//@version=5
strategy("Exit reservation trailing mixed side precedence")
if bar_index == 0
    strategy.entry("L", strategy.long, qty=2)
    strategy.exit("XT", "L", trail_price=2, trail_offset=50, qty=0.5)
if bar_index == 2
    strategy.exit("XL", "L", limit=3.8, qty=0.5)
    strategy.exit("XB", "L", stop=2.5, limit=3.85, qty=0.5)
plot(strategy.position_size)
plot(strategy.netprofit)
plot(strategy.closedtrades)
plot(strategy.opentrades)
