//@version=5
strategy("Closed trade fields")
if bar_index == 0
    strategy.entry("L", strategy.long, qty=2)
if bar_index == 2
    strategy.close("L")
plot(strategy.closedtrades.entry_price(0))
plot(strategy.closedtrades.exit_price(0))
plot(strategy.closedtrades.entry_bar_index(0))
plot(strategy.closedtrades.exit_bar_index(0))
plot(strategy.closedtrades.entry_time(0))
plot(strategy.closedtrades.exit_time(0))
plot(strategy.closedtrades.commission(0))
plot(strategy.closedtrades.size(0))
plot(strategy.closedtrades.profit(0))
plot(strategy.closedtrades.entry_price(1))
