//@version=5
strategy("Exit reservation interactions")
stop_price = switch bar_index
    0 => 2.5
    => 10.0
limit_price = switch bar_index
    0 => 1.5
    => 10.0
if bar_index == 0
    for i = 0 to 0
        strategy.entry("L", strategy.long, qty=2)
    strategy.exit("XS", "L", stop=stop_price, qty=0.5)
    j = 0
    while j < 1
        strategy.exit("XL", "L", limit=limit_price, qty=1.5)
        j := j + 1
plot(strategy.position_size)
plot(strategy.netprofit)
