//@version=5
strategy("Strategy variable interactions")

as_tens(value) => value * 10

if bar_index == 1
    strategy.entry("L", strategy.long, qty=2)

if_value = strategy.position_size * 0
if strategy.position_size > 0
    if_value := strategy.position_size
else
    if_value := -1.0

direction = strategy.position_size > 0 ? 1 : 0
switch_value = switch direction
    1 => strategy.position_size + strategy.openprofit
    => -1.0

for_value = strategy.position_size * 0
for i = 0 to 1
    for_value := for_value + strategy.position_size

while_value = strategy.position_size * 0
j = 0
while j < strategy.position_size
    while_value := while_value + 1
    j := j + 1

plot(if_value)
plot(switch_value)
plot(for_value)
plot(while_value)
plot(as_tens(strategy.position_size))
plot(strategy.position_size[1])
plot(strategy.openprofit[1])

if bar_index == 2
    strategy.close("L")
