//@version=5
strategy("Position state strategy", overlay=true)
identity(value) => value
plot(strategy.position_size)
plot(strategy.position_avg_price)
if bar_index == 1
    strategy.entry("L", strategy.long, qty=2)
plot(strategy.position_size)
plot(strategy.position_avg_price)
independent_position_avg_price = strategy.position_avg_price * 0
position_avg_price_i = 0
while position_avg_price_i < 1
    independent_position_avg_price := strategy.position_avg_price
    position_avg_price_i := position_avg_price_i + 1
plot(independent_position_avg_price)
plot(identity(strategy.position_avg_price))
if bar_index == 2
    strategy.close("L")
plot(strategy.position_size)
plot(strategy.position_avg_price)
plot(strategy.max_contracts_held_all)
plot(identity(strategy.max_contracts_held_all))
independent_max_contracts_held_all = strategy.max_contracts_held_all * 0
max_contracts_held_all_i = 0
while max_contracts_held_all_i < 1
    independent_max_contracts_held_all := strategy.max_contracts_held_all
    max_contracts_held_all_i := max_contracts_held_all_i + 1
plot(independent_max_contracts_held_all)
plot(strategy.max_contracts_held_long)
independent_max_contracts_held_long = strategy.max_contracts_held_long * 0
max_contracts_held_long_i = 0
while max_contracts_held_long_i < 1
    independent_max_contracts_held_long := strategy.max_contracts_held_long
    max_contracts_held_long_i := max_contracts_held_long_i + 1
plot(independent_max_contracts_held_long)
plot(strategy.max_contracts_held_short)
independent_max_contracts_held_short = strategy.max_contracts_held_short * 0
max_contracts_held_short_i = 0
while max_contracts_held_short_i < 1
    independent_max_contracts_held_short := strategy.max_contracts_held_short
    max_contracts_held_short_i := max_contracts_held_short_i + 1
plot(independent_max_contracts_held_short)
