//@version=5
strategy("Exit reservation bracket state", initial_capital=1000)
if bar_index == 0
    strategy.entry("L", strategy.long, qty=2)
    strategy.exit("XS", "L", stop=2.5, qty=0.5)
    strategy.exit("XB", "L", stop=0.25, limit=3, qty=1.5)
plot(strategy.position_size)
plot(strategy.position_avg_price)
plot(strategy.openprofit)
plot(strategy.netprofit)
plot(strategy.equity)
plot(strategy.closedtrades)
plot(strategy.opentrades)
