//@version=6
strategy("Trade counts")
identity(value) => value

plot(strategy.closedtrades)
plot(strategy.opentrades)

if bar_index == 1
    strategy.entry("L", strategy.long, qty=1)

plot(strategy.closedtrades)
plot(strategy.opentrades)
independent_opentrades = strategy.opentrades * 0
opentrades_i = 0
while opentrades_i < 1
    independent_opentrades := strategy.opentrades
    opentrades_i := opentrades_i + 1

if bar_index == 2
    strategy.close("L")

if bar_index == 3
    strategy.close("L")

plot(strategy.closedtrades)
plot(strategy.opentrades)
independent_closedtrades = strategy.closedtrades * 0
closedtrades_i = 0
while closedtrades_i < 1
    independent_closedtrades := strategy.closedtrades
    closedtrades_i := closedtrades_i + 1
plot(independent_closedtrades)
plot(independent_opentrades)
plot(strategy.closedtrades[1])
plot(strategy.opentrades[1])
plot(strategy.closedtrades.first_index)
plot(identity(strategy.closedtrades.first_index))
plot(strategy.closedtrades.first_index[1])
