//@version=5
strategy("Trailing interactions")

adjust(value) =>
    value

activation = switch bar_index
    0 => adjust(2.5)
    => adjust(2.5)

if bar_index == 0
    for i = 0 to 0
        j = 0
        while j < 1
            strategy.entry("L", strategy.long, qty=2)
            strategy.exit("XT", "L", trail_price=activation, trail_offset=50)
            j := j + 1

plot(strategy.position_size)
plot(strategy.position_size[1])
plot(strategy.netprofit)
