//@version=5
strategy("Pyramiding close", pyramiding=2)

if bar_index == 0
    strategy.entry("L1", strategy.long, qty=1)
if bar_index == 1
    strategy.entry("L2", strategy.long, qty=3)
if bar_index == 2
    strategy.close("L1")
if bar_index == 3
    strategy.close("L2")

plot(strategy.opentrades)
plot(strategy.position_size)
plot(strategy.position_avg_price)
plot(strategy.closedtrades)
plot(strategy.opentrades.entry_id(0) == "L2" ? 1 : 0)
