//@version=5
strategy("Position state strategy", overlay=true)
identity(value) => value
position_entry_name = strategy.position_entry_name
position_entry_name_udf = identity(strategy.position_entry_name)
position_entry_name_history = strategy.position_entry_name[1]
account_currency = strategy.account_currency
account_currency_udf = identity(strategy.account_currency)
account_currency_history = strategy.account_currency[1]
plot(strategy.position_size)
plot(strategy.position_avg_price)
if bar_index == 1
    strategy.entry("L", strategy.long, qty=2)
plot(strategy.position_size)
plot(strategy.position_avg_price)
independent_position_avg_price = strategy.position_avg_price * 0
position_avg_price_i = 0
while position_avg_price_i < 1
    independent_position_avg_price := strategy.position_avg_price
    position_avg_price_i := position_avg_price_i + 1
plot(independent_position_avg_price)
plot(identity(strategy.position_avg_price))
position_avg_price_history = strategy.position_avg_price[1]
if bar_index == 2
    strategy.close("L")
plot(strategy.position_size)
plot(strategy.position_avg_price)
plot(strategy.max_contracts_held_all)
plot(identity(strategy.max_contracts_held_all))
independent_max_contracts_held_all = strategy.max_contracts_held_all * 0
max_contracts_held_all_i = 0
while max_contracts_held_all_i < 1
    independent_max_contracts_held_all := strategy.max_contracts_held_all
    max_contracts_held_all_i := max_contracts_held_all_i + 1
plot(independent_max_contracts_held_all)
plot(strategy.max_contracts_held_long)
plot(identity(strategy.max_contracts_held_long))
independent_max_contracts_held_long = strategy.max_contracts_held_long * 0
max_contracts_held_long_i = 0
while max_contracts_held_long_i < 1
    independent_max_contracts_held_long := strategy.max_contracts_held_long
    max_contracts_held_long_i := max_contracts_held_long_i + 1
plot(independent_max_contracts_held_long)
plot(strategy.max_contracts_held_short)
plot(identity(strategy.max_contracts_held_short))
independent_max_contracts_held_short = strategy.max_contracts_held_short * 0
max_contracts_held_short_i = 0
while max_contracts_held_short_i < 1
    independent_max_contracts_held_short := strategy.max_contracts_held_short
    max_contracts_held_short_i := max_contracts_held_short_i + 1
plot(independent_max_contracts_held_short)
plot(position_avg_price_history)
plot(strategy.max_contracts_held_all[1])
plot(strategy.max_contracts_held_long[1])
plot(strategy.max_contracts_held_short[1])
plot(na(position_entry_name) ? na : position_entry_name == "L" ? 1 : 0)
plot(na(position_entry_name_udf) ? na : position_entry_name_udf == "L" ? 1 : 0)
plot(na(position_entry_name_history) ? na : position_entry_name_history == "L" ? 1 : 0)
plot(account_currency == "USD" ? 1 : 0)
plot(account_currency_udf == "USD" ? 1 : 0)
plot(na(account_currency_history) ? na : account_currency_history == "USD" ? 1 : 0)
