//@version=5
strategy("Trade outcome counts")

if bar_index == 0
    strategy.entry("W", strategy.long, qty=1)

if bar_index == 2
    strategy.close("W")

if bar_index == 3
    strategy.entry("L", strategy.long, qty=1)

if bar_index == 5
    strategy.close("L")

if bar_index == 6
    strategy.entry("E", strategy.long, qty=1)

if bar_index == 8
    strategy.close("E")

plot(strategy.wintrades)
plot(strategy.losstrades)
plot(strategy.eventrades)
plot(strategy.closedtrades)
plot(strategy.grossprofit)
plot(strategy.grossloss)
plot(strategy.avg_trade)
plot(strategy.avg_trade_percent)
plot(strategy.avg_winning_trade)
plot(strategy.avg_winning_trade_percent)
plot(strategy.avg_losing_trade)
plot(strategy.avg_losing_trade_percent)
independent_wintrades = strategy.wintrades * 0
wintrades_i = 0
while wintrades_i < 1
    independent_wintrades := strategy.wintrades
    wintrades_i := wintrades_i + 1
plot(independent_wintrades)
independent_losstrades = strategy.losstrades * 0
losstrades_i = 0
while losstrades_i < 1
    independent_losstrades := strategy.losstrades
    losstrades_i := losstrades_i + 1
plot(independent_losstrades)
independent_eventrades = strategy.eventrades * 0
eventrades_i = 0
while eventrades_i < 1
    independent_eventrades := strategy.eventrades
    eventrades_i := eventrades_i + 1
plot(independent_eventrades)
independent_grossprofit = strategy.grossprofit * 0
grossprofit_i = 0
while grossprofit_i < 1
    independent_grossprofit := strategy.grossprofit
    grossprofit_i := grossprofit_i + 1
plot(independent_grossprofit)
