//@version=5
strategy("Close entries rule ANY close short", pyramiding=2, close_entries_rule="ANY")

if bar_index == 0
    strategy.entry("older", strategy.short, qty=1)
if bar_index == 1
    strategy.entry("target", strategy.short, qty=2)
if bar_index == 2
    strategy.close("target")

plot(strategy.closedtrades)
plot(strategy.closedtrades.entry_id(0) == "target" ? 1 : 0)
plot(strategy.position_size)
