//@version=5
strategy("Open trade fields")
if bar_index == 0
    strategy.entry("L", strategy.long, qty=2)
if bar_index == 2
    strategy.close("L")
plot(strategy.opentrades.entry_price(0))
plot(strategy.opentrades.entry_bar_index(0))
plot(strategy.opentrades.entry_time(0))
plot(strategy.opentrades.entry_price(1))
plot(strategy.opentrades.entry_bar_index(1))
plot(strategy.opentrades.entry_time(1))
plot(strategy.opentrades.entry_price(-1))
plot(strategy.opentrades.entry_bar_index(-1))
plot(strategy.opentrades.entry_time(-1))
plot(strategy.opentrades.entry_price(0.5))
plot(strategy.opentrades.entry_bar_index(0.5))
plot(strategy.opentrades.entry_time(0.5))
