//@version=5
strategy("Close entries rule ANY same id partial exit", pyramiding=2, close_entries_rule="ANY")

if bar_index == 0
    strategy.entry("L", strategy.long, qty=1)
if bar_index == 1
    strategy.entry("L", strategy.long, qty=3)
if bar_index == 2
    strategy.exit("XL", from_entry="L", limit=5, qty=1.5)

plot(strategy.closedtrades)
plot(strategy.closedtrades.entry_id(0) == "L" ? 1 : 0)
plot(strategy.closedtrades.entry_id(1) == "L" ? 1 : 0)
plot(strategy.position_size)
