//@version=5
strategy("Strategy close metadata", overlay=true)
message = close > open ? "up" : "down"
if bar_index == 0
    strategy.entry("L", strategy.long, qty=2)
if bar_index == 1
    strategy.close("L", comment="close", alert_message=message, disable_alert=false)
if bar_index == 2
    strategy.entry("L2", strategy.long, qty=1)
if bar_index == 3
    strategy.close_all(comment="close all", alert_message=message, disable_alert=true)
plot(strategy.closedtrades)
