//@version=5
indicator("Table delete")
var table_id = table.new(position.top_right, 2, 2)
if bar_index == 1
    table.cell(table_id, 0, 0, "A")
    table.delete(table_id)
if bar_index == 2
    table.cell(table_id, 0, 0, "ignored")
    table.set_bgcolor(table_id, color.red)
    table.delete(table_id)
table.delete(na)
plot(close)
var loop_table = table.new(position.bottom_left, 1, 1)
i = 0
while i < 1
    if bar_index == 2
        table.delete(loop_table)
    i := i + 1
