//@version=5
indicator("Table merge cells")
var table_id = table.new(position.top_right, 4, 3)
if bar_index == 1
    table.cell(table_id, 0, 0, "Header")
    table.merge_cells(table_id, 0, 0, 3, 0)
    table.cell(table_id, 0, 1, "Body", bgcolor=color.green)
    table.merge_cells(table_id, 0, 1, 1, 2)
if bar_index == 2
    i = 0
    while i < 1
        table.merge_cells(table_id, 2, 1, 3, 1)
        i := i + 1
    table.clear(table_id, 0, 1, 1, 2)
    table.clear(table_id, 2, 1, 3, 1)
    table.delete(table_id)
    table.merge_cells(table_id, 2, 1, 3, 2)
table.merge_cells(na, 0, 0, 0, 0)
plot(close)
