//@version=5
indicator("Table control flow")
var table_id = table.new(position.top_right, 2, 2)
if bar_index == 1
    table.cell(table_id, 0, 0, "if")
direction = close > open ? 1 : -1
switch direction
    1 => table.cell(table_id, 1, 0, "up", bgcolor=color.green)
    => table.cell(table_id, 1, 0, "down", bgcolor=color.red)
for i = 0 to 0
    if bar_index == 2
        table.cell(table_id, 0, 1, "for")
j = 0
while j < 1
    if bar_index == 3
        table.cell(table_id, 1, 1, "while", text_color=color.white)
    j := j + 1
plot(close)
k = 0
while k < 1
    if bar_index == 3
        table.set_position(table_id, position.bottom_right)
        table.set_bgcolor(table_id, color.yellow)
        table.set_frame_color(table_id, color.black)
        table.set_frame_width(table_id, 3)
    k := k + 1
