//@version=5
indicator("User type array typed UDF params")

type Point
    float x
    float y

first_x(array<Point> values) =>
    point = array.get(values, 0)
    point.x

second_y(Point[] values) =>
    point = values.get(1)
    point.y

points = array.from(Point.new(close + 1, open + 2), Point.new(high + 3, low + 4))
value = first_x(points) + second_y(points)
previous = value[1]

plot(value)
plot(previous)
