//@version=5
indicator("VWAP edge cases")
source = bar_index == 3 ? na : close
anchor = bar_index == 1
multiplier = close / 10
plot(ta.vwap)
plot(ta.vwap(close))
plot(ta.vwap(close, anchor))
[basis, upper, lower] = ta.vwap(source, anchor, multiplier)
[missing_mult_basis, missing_mult_upper, missing_mult_lower] = ta.vwap(close, timeframe.change("1D"), na)
plot(basis)
plot(upper)
plot(lower)
plot(na(missing_mult_basis) and na(missing_mult_upper) and na(missing_mult_lower) ? 1 : 0)
plot(ta.vwap(source))
