//@version=5
indicator("User type typed var rollback")
type Point
    float x

var Point p = na
if bar_index == 0
    p := Point.new(close)
else
    p := Point.new(p.x + 1)
plot(p.x)
var Point q = if bar_index == 0
    Point.new(close + 10)
else
    Point.new(close + 20)
if bar_index > 0
    q := Point.new(q.x + 1)
plot(q.x)
var Point r = bar_index == 0 ? Point.new(close + 30) : Point.new(close + 40)
if bar_index > 0
    r := Point.new(r.x + 1)
plot(r.x)
